#define SPEED 402
#define ANIM (SPEED+NUMTILE16)

#define NORTHWALL (ANIM+NUMTILE16)
#define EASTWALL (NORTHWALL+NUMTILE16M)
#define SOUTHWALL (EASTWALL+NUMTILE16M)
#define WESTWALL (SOUTHWALL+NUMTILE16M)
#define MANIM (WESTWALL+NUMTILE16M)
#define INTILE (MANIM+NUMTILE16M)
#define MSPEED (INTILE+NUMTILE16M)
